<#include "common/headerShort.ftlh">

<header class="jumbotron">
    <div class="container">
        <h1 class="display-3">Shopping list</h1>
        <p>
            Strona 4Fun
        </p>
    </div>
</header>

<main role="main">
    <div class="container">
        <div class="row">
            <h2> :) Nowy produkt został dodany. :) </h2>
        </div>
    </div>
</main>

<#include "common/copyright-footer.ftlh">
